### ISSUE TITLE
Hackagotchi got deleted

### ISSUE THREAD

**Issue by nzeng8** [hackagotchi/hackagotchi#101] opened 2020-07-11 14:54 UTC
I'm not sure if this is related to #85 or not, since this was recently fixed, but now I only have one gempheus instead of two D:

**Comment by nzeng8** [comment] 2020-07-12 05:56
The gempheus appears to be in the database but does not show up on slack

**Comment by Muirrum** [comment] 2020-07-12 17:16
If I had to guess it's related to the slack API limitation on JSON object size

**Comment by saharshy29** [comment] 2020-07-12 17:30
What do you mean that it got deleted? It seems fine to me.

**Comment by Muirrum** [comment] 2020-07-12 17:37
Nick is referring to the actual 'gotchi that are in-game resources, not the slack app itself

**Comment by lukec11** [comment] 2020-07-14 06:37
Duplicate of #50

**Closed by lukec11** 2020-07-14 06:37 UTC
Labels: bug, slack-api
