### ISSUE TITLE
Hackagotchi's GP pool can be emptied with a POST request

### ISSUE THREAD

**Issue by lukec11** [hackagotchi/hackagotchi#80] opened 2020-06-29 01:46 UTC
Because the POSTs from slack are unverified, someone could send a POST as slack and initiate a special user message that would `gp_dump`. This could let unauthorized people empty hackagotchi's gp into their own accounts. 

This is potentially related to #65 , because both are caused by lack of verification from slack.

This verification could happen by checking the headers as the requests come in from slack, and ensure that they are signed with what slack calls a "signing secret."

**Comment by hkatzdev** [comment] 2020-06-29 01:47
Duplicate of #65

**Comment by lukec11** [comment] 2020-06-29 01:48
@hkatzdev : I also opened #65 , and while they are related, they are not the same issue. That one can cause a server panic, this one can break the game by radically changing the economy.

**Closed by hkatzdev** 2020-06-29 01:47 UTC
Labels: duplicate

**Comment by hkatzdev** [comment] 2020-06-29 01:49
They are both related to slack header verification with the goblin command.

**Comment by hkatzdev** [comment] 2020-06-29 01:49
Nice try to get powder though :wink:

**Comment by lukec11** [comment] 2020-06-29 01:51
Not an attempt to get powder - currently I'm at 100 warp powder, I don't see a need to get 2 more (if that's being given out anyway - it was my understanding that a system to paying out for PRs was being put in place). Again, I've acknowledged (in the original issue!) that these two were related - they are - but they are not the same issue.

**Comment by hkatzdev** [comment] 2020-06-29 01:52
They are the exact same underlining problem. We do not need a separate issue for every single API call.
