### ISSUE TITLE
Can hatch a Nest Egg multiple times

### ISSUE THREAD

**Issue by nguyenadam** [hackagotchi/hackagotchi#139] opened 2020-07-26 20:39 UTC
While I was hatching my first egg, Slack was lagging and I ended up clicking the hatch button 4 times, which gave me 4X the resources.

**Comment by nzeng8** [comment] 2020-07-26 20:45
![Screen Shot 2020-07-26 at 1 44 05 PM](https://user-images.githubusercontent.com/53419893/88488995-3873e080-cf46-11ea-8305-84179d740a1b.png)
![Screen Shot 2020-07-26 at 1 44 15 PM](https://user-images.githubusercontent.com/53419893/88488998-3d389480-cf46-11ea-975b-5371f181217e.png)
![Screen Shot 2020-07-26 at 1 44 21 PM](https://user-images.githubusercontent.com/53419893/88489001-40338500-cf46-11ea-9276-90aee7bfe7ca.png)
![Screen Shot 2020-07-26 at 1 44 28 PM](https://user-images.githubusercontent.com/53419893/88489003-432e7580-cf46-11ea-9095-86610e0e0b6e.png)
![Screen Shot 2020-07-26 at 1 44 36 PM](https://user-images.githubusercontent.com/53419893/88489004-4590cf80-cf46-11ea-816e-53d523be9f4b.png)

**Comment by LinusS1** [comment] 2020-07-27 00:13
I can't reproduce this on my slack app in iOS 14.
However, I can on my computer. I clicked the `Hatch` Button a lot, and it hatched 2 times.
When using (spamming) the command `/egghatchwhen` before the egg hatch message it said repeatedly that it had hatched an egg. Only one egg was hatched.

**Comment by lukec11** [comment] 2020-07-30 17:44
This is a duplicate of #75 - the server needs to do verification, because sometimes spamming the button can cause slack to send multiple requests (and the server will respond to both). Closing this, but feel free to follow the progress over there.

**Closed by lukec11** 2020-07-30 17:44 UTC
Labels: Priority: Medium, bug
